steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/divya-classes', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/divya-classes' ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud run deploy divya-classes \
      --image gcr.io/$PROJECT_ID/divya-classes \
      --region=us-central1 \
      --platform=managed \
      --allow-unauthenticated \
      --set-env-vars DJANGO_DEBUG=False,DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
images:
- 'gcr.io/$PROJECT_ID/divya-classes'
