# Generated by Django 5.2.7 on 2025-10-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('standard', models.CharField(choices=[('8th', '8th'), ('9th', '9th'), ('10th', '10th (SSC/HSC/CBSE)'), ('11th', '11th (HSC/CBSE)'), ('12th', '12th (HSC/CBSE)'), ('JEE', 'JEE'), ('NEET', 'NEET'), ('CET', 'CET')], max_length=20)),
                ('message', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
